BOARD_TAG    = uno
#ARDUINO_PORT = /dev/cu.usb*
ARDUINO_PORT = /dev/ttyACM0
USER_LIB_PATH = lib
ARDUINO_LIBS = avr-stl nanopb
ARDUINO_CPPFLAGS = GOOGLE_PROTOBUF_NO_RTTI
AVR_TOOLS_DIR = /etc
AVR_TOOLS_PATH = /usr/bin

ARDUINO_DIR=/usr/share/arduino
ARDMK_DIR=lib/arduino-makefile
include $(ARDMK_DIR)/arduino-mk/Arduino.mk
